### ISSUE TITLE
Searching for multiple rooms in C3 Building

### ISSUE THREAD

**Issue by JGerth92** [soft-eng-practicum/ggcmaps#33]
### Description:
When searching for a room in the C3 Building on the 1st and/or 2nd floor without using the 'C' prefix the search is reformed in such a way as to disallow future searches without completely retyping the search.

### Recreate by:
* Navigate to the 1st floor of C3
* Search for room 1314 (search is reformatted C 31319 instead of C 1319.)
* Try searching for another room on that floor (1313) (no error is thrown but the map doesn't change either.)

### Time Log:
| User | Date  | Start Time | End Time | Total |
| ----- | ------ | ----------- | ---------- |------ |
| JGerth92 | 3/10/2017 | 02:00 | 02:03 | 0:03 |

**Comment by Dave89rr** [comment]
@JGerth92 tomorrow when you get the chance, please test my branch on the latest commit (af60d28), because I can't recreate this issue.

### Steps Taken:
* Loaded site
* Clicked on C3
* Typed "1314" in search bar; hit Enter
[Room Highlights]
* Cleared Search Bar; typed in "1343"; hit enter
[Room Highlights]

Alt:
* Loaded Site
* Typed in "C"; hit enter
* Typed "1314"; hit enter
[Room Highlights]
* Cleared Search bar; Typed 1343; hit enter
[Room highlights]

The formatting is appearing as you state above, but I'm not getting the lack of highlight problem
