### ISSUE TITLE
3000 Rooms Not Searchable

### ISSUE THREAD

**Issue by Dave89rr** [soft-eng-practicum/ggcmaps#52]
### Description:
3000 rooms are not searchable (even after initial modifications to `rooms.js`.

**Comment by Dave89rr** [comment]
Part of issue #37

**Comment by miked49er** [comment]
3000 building is searchable, but using the wrong notation. To search for a room in 3000 building like '3101D' in from the campus map, you have to search '3 3101D'. The proper way to denote this room would be 'RL 3101D'. The search algorithm should be updated to use 'RL' instead of '3' to denote 3000 building.

**Comment by cengique** [comment]
Actually, from the 3000 building view, it can find rooms. But I didn't realize it wasn't working on the campus level. 
I think users shouldn't need to put the RL prefix. One can distinguish 3000 rooms if you are at the campus level and you don't put a building prefix. Also, autocomplete could help in putting the RL prefix if necessary.

**Comment by miked49er** [comment]
I've checked how the rooms are listed by GGC and that is it. Professors that have offices in the 3000 Building list it as RL-3101D or whatever the room is.

**Comment by cengique** [comment]
Oh, ok. That makes sense, then.

**Comment by imtinguyen** [comment]
Fixed with commit 73036a0
